### ISSUE TITLE
这个插件怎么配置生成的项目的位置啊

### ISSUE THREAD

**Issue by qiugu** [easy-team/vscode-easy-plugin#1]
如题，怎么修改项目安装的目录

**Comment by hubcarl** [comment]
@willworks @jasonjcpeng 帮忙看一下

**Comment by willworks** [comment]
@qiugu https://github.com/easy-team/vscode-easy-plugin/blob/master/extension.js#L29 目前默认是在 ~/easy 目录下，需要适配下，可以加一个配置/全路径输入

**Comment by qiugu** [comment]
具体在哪里配置呢，没看明白

**Comment by hubcarl** [comment]
@qiugu @willworks  已发布 1.1.0

**Comment by willworks** [comment]
更新下插件，然后看着 [READNE](https://github.com/easy-team/vscode-easy-plugin#configuration) 来配置，支持直接输入文件目录，还有全局配置 @qiugu
